version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "ssu-schedule-db"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql