basePath: /api/v1.0
definitions:
  model.Departments:
    properties:
      full_name:
        type: string
      id:
        type: integer
      short_name:
        type: string
      url:
        type: string
    type: object
  model.Groups:
    properties:
      department_id:
        type: integer
      education_form:
        type: string
      group_num:
        type: string
      id:
        type: integer
    type: object
  model.StudentsLesson:
    properties:
      day_num:
        type: integer
      id:
        type: integer
      lesson_name:
        type: string
      lesson_place:
        type: string
      lesson_type:
        type: string
      subgroup_name:
        type: string
      teacher:
        type: string
      week_type:
        type: string
    type: object
  model.Subgroups:
    properties:
      group_id:
        type: integer
      subgroup_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for SSU Schedule Application
  title: SSU Schedule API
  version: "1.0"
paths:
  /{education_form}/{department}/{group_number}:
    get:
      consumes:
      - application/json
      description: Retrieves the schedule based on department, education form and
        group number
      operationId: get-students-schedule
      parameters:
      - description: Education form, e.g. `do`
        in: path
        name: education_form
        required: true
        type: string
      - description: Department URL, e.g. `knt` for CSIT department
        in: path
        name: department
        required: true
        type: string
      - description: Group number, e.g. `351`
        in: path
        name: group_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StudentsLesson'
            type: array
      summary: get the schedule of students for a particular group
      tags:
      - schedule
  /{education_form}/{department}/{group_number}/subgroups:
    get:
      consumes:
      - application/json
      description: Retrieves the subgroups list of a group based on department, education
        form and group number
      operationId: get-group-subgroups
      parameters:
      - description: Education form, e.g. `do`
        in: path
        name: education_form
        required: true
        type: string
      - description: Department URL, e.g. `knt` for CSIT department
        in: path
        name: department
        required: true
        type: string
      - description: Group number, e.g. `351`
        in: path
        name: group_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subgroups'
            type: array
      summary: get a list of subgroups of a certain group
      tags:
      - groups
  /{education_form}/{department}/groups:
    get:
      consumes:
      - application/json
      description: Retrieves groups' list based on department and education form
      operationId: get-groups-list
      parameters:
      - description: Education form, e.g. `do`
        in: path
        name: education_form
        required: true
        type: string
      - description: Department URL, e.g. `knt` for CSIT department
        in: path
        name: department
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Groups'
            type: array
      summary: get a list of groups of a certain department
      tags:
      - groups
  /departments:
    get:
      description: Retrieves SSU departments' list
      operationId: get-departments-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Departments'
            type: array
      summary: get a list of departments
      tags:
      - departments
swagger: "2.0"
